<?php
declare(strict_types=1);

namespace FloCMS\Core\Modules;

use RuntimeException;

final class ModuleSynchronizer
{
    public function __construct(
        private readonly ModulePaths $paths,
        private readonly ModuleDiscovery $discovery
    ) {
    }

    /**
     * @return array{count: int, modules: list<string>, cache: string, fingerprint: string}
     */
    public function sync(): array
    {
        $registry = $this->discovery->discover();
        $modules = [];

        foreach ($registry->all() as $module) {
            $basePath = $this->paths->relativeToRoot($module->basePath) ?? $module->basePath;
            $modules[] = $module->toArray(str_replace(DIRECTORY_SEPARATOR, '/', $basePath));
        }

        $compiled = [
            'schema' => 1,
            'generated_at' => gmdate('c'),
            'fingerprint' => $registry->fingerprint($this->paths),
            'modules' => $modules,
        ];

        if (is_file($this->paths->registryCache)) {
            $existing = require $this->paths->registryCache;
            if (
                is_array($existing)
                && (int) ($existing['schema'] ?? 0) === 1
                && hash_equals(
                    (string) ($existing['fingerprint'] ?? ''),
                    $compiled['fingerprint']
                )
                && ($existing['modules'] ?? null) === $modules
            ) {
                return [
                    'count' => count($modules),
                    'modules' => array_values(array_keys($registry->all())),
                    'cache' => $this->paths->registryCache,
                    'fingerprint' => $compiled['fingerprint'],
                ];
            }
        }

        $content = "<?php\ndeclare(strict_types=1);\n\n"
            . "// Generated by Flo Framework's module synchronizer. Do not edit.\n"
            . 'return ' . var_export($compiled, true) . ";\n";

        $this->writeAtomically($this->paths->registryCache, $content);

        return [
            'count' => count($modules),
            'modules' => array_values(array_keys($registry->all())),
            'cache' => $this->paths->registryCache,
            'fingerprint' => $compiled['fingerprint'],
        ];
    }

    private function writeAtomically(string $path, string $content): void
    {
        if (is_file($path) && file_get_contents($path) === $content) {
            return;
        }

        $directory = dirname($path);
        if (!is_dir($directory) && !mkdir($directory, 0755, true) && !is_dir($directory)) {
            throw new RuntimeException('Unable to create module cache directory: ' . $directory);
        }

        try {
            $suffix = bin2hex(random_bytes(8));
        } catch (\Throwable) {
            $suffix = str_replace('.', '', uniqid('', true));
        }
        $temporary = $path . '.' . $suffix . '.tmp';

        if (file_put_contents($temporary, $content, LOCK_EX) === false) {
            throw new RuntimeException('Unable to write temporary module cache: ' . $temporary);
        }

        if (!rename($temporary, $path)) {
            @unlink($temporary);
            throw new RuntimeException('Unable to publish compiled module registry: ' . $path);
        }

        @chmod($path, 0644);
    }
}
